const { runInviteScript } = require('./puppeteer_core');

const cookieStr = `[
    {
        "name": "_puid",
        "value": "user-SvNJxqYl92ma7YnTYAX5hyrz:1783336932-ngfzasvGHJNpyKtXqUY3rnUSky1j71TuhV6hajSWDh8%3D",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1783941732,
        "storeId": null
    },
    {
        "name": "__oailb",
        "value": "eyJhbGciOiJFUzI1NiIsImtpZCI6Im9haWxiLXYxIiwidHlwIjoiSldUIn0.eyJob3N0IjoiY2hhdC5nYXRld2F5LnVuaWZpZWQtMTY0LmFwaS5vcGVuYWkuY29tIiwiaXNzIjoiZWRnZS1nYXRld2F5IiwiYXVkIjpbImNoYXRncHQuY29tIl0sImV4cCI6MTc4MzAwMzQxOCwiaWF0IjoxNzgyOTk5NTE4fQ.6-0VX7u8Tzk6x0LB0KWZy8rNvygZOqoLycy9QEJMYxK-vRbNBhTal_PJYPS966sph3y5IIAPkiPDW1jtVAT4gQ",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1783003118,
        "storeId": null
    },
    {
        "name": "__cflb",
        "value": "0H28vzvP5FJafnkHxigzJ74Ls2JzWafvzyP8RLHuYrf",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1783339899,
        "storeId": null
    },
    {
        "name": "oai-hlib",
        "value": "true",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1814080564,
        "storeId": null
    },
    {
        "name": "cf_clearance",
        "value": "gJPwEktidh0QRnaMAh8.98k0o3.ZNSETZrTQa_D88Vs-1783336300-1.2.1.1-BOqE3vH7flUAp0eVyou6j6gtlDVMSh.6_MmMd3oObguPzCSg2o8QAyr9DB7zdRd0pOtIJ1h9IxaDL7Rd7Q.wwr6Wl63wllfpCuDhB2Am.hvCo5iFT_WfQh1PpNOlmX164PWW9sfoVaR8reIzL8GYSsSy6tQoJjpp4lwRcJI.2YBLj3drWbNtnWpYJ_q3EziH8WIXXst4yvHJd.TqDGAoppzK40fFSrNL6UMzX2Y98DhwSyIKnH5e8DdCxipuOnMLHVol7SvEdGTUG0MF7PhOAAMWXx.YGdxBmP7yF_pE3y9xjH7F9FoJT.LySPzaU4yn.7lKpxFoi98FlEhxOUEwJw",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1814872300,
        "storeId": null
    },
    {
        "name": "oai_consent_marketing",
        "value": "false",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1798528566,
        "storeId": null
    },
    {
        "name": "_dd_s",
        "value": "aid=88934295-f841-4683-9759-cb857b01f6ae&rum=0&expire=1783337830736&logs=1&id=4b387f99-b8e5-4919-a9a7-6ada6cb634bf&created=1783336301215",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "strict",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1814872930,
        "storeId": null
    },
    {
        "name": "oai_consent_analytics",
        "value": "false",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1798528566,
        "storeId": null
    },
    {
        "name": "__cf_bm",
        "value": "_OVf7ErOw1m7b30bNIVewUsKScRvZ1leCcZjwFdxc4g-1783336300.951374-1.0.1.1-eUIm.DlkSgyy57vjZKnzjN95bySjG_EHp8lprZr6Ykvguqk2mFcGVoFK.NNnmt5IQIQwfhWcKJBRruoqNP8w9K0ELhPehpLJaTYxTDo8QSuq89IVSBEFp70RFCITdaA3",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1783338100,
        "storeId": null
    },
    {
        "name": "_cfuvid",
        "value": "2mSnVwcPTXH6h9L2yCuRilO8qXP3PNs634C4WBIXM3c-1783336299.4811025-1.0.1.1-yvcwnL2kLY9FaDg40tZvtCymJwTvryHkeL.CHvsHk_8",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "oai_consent_personalization",
        "value": "false",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1798528566,
        "storeId": null
    },
    {
        "name": "oai-sc",
        "value": "0gAAAAABqS4_lk4X-n_BWbjEB__0ycT6AR5XFXNJNcXYkXjOjIAuxwlZvDYfoRE_lmvXtVPFK1IdSx1Odo7p63PeW1gpnVk8CHAWrU9JAY2iK_p75yMtbJotESNpRIRVjtytK_g23udSFGLv8n8cjNytat4JnQ5OiIl3X4Y8r8bdM3Bka3btW3sPHUPfdAlq-CGZOuQTER00GfMOpLXdLq_xdavaaXNo478q8Y4xJxeyFNssn2VcCcd4",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1814872933,
        "storeId": null
    },
    {
        "name": "oai-gn",
        "value": "Winda",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "__Secure-next-auth.session-token.1",
        "value": "EjGvHWvrvMv7Oimj5AsdhC9LKZuJKEZn6CRdRxe6myAS-YbaDI8NcTJc1S54DJTZRuauBatazSm79EMW7PJOn4N3iw474jqxGbXRMmYSqk-Hr6u9XsNkOWeajOtFP6UNtFagezmRJffeKj-R7ad0Mn6eQ9LHtf3oXssm21X87x69l14Hckkf0G99qxTn7WM0qoUr9P7PFFDbaEwG2aA9z0vlNZH3nvjydPS7fhXBgX3ECJnnzr5e3eZDgOZ_LOB_BaxK9JCzH1GY6BGAK_okyuPiFFGLUsOk6K5DzpQA670K5AOcBc_A525XkT69JWBVYXBeao1UhBtaiO1271jfwEgRXcnZf0JOc5GhkGcRk930kgyxsZZaltsKv6Z9LnWy_XJeCC9gMD9lirgbGyMOd2VqKbM_5-ng.cvnbzz7ilKdMd8bytPUnqg",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1791112929,
        "storeId": null
    },
    {
        "name": "_uasid",
        "value": "\"Z0FBQUFBQnFSaEVGRzQxbEVEekJwdDVIYzZta3YzM0NZUGhuRUc3VkdSZ19DQVJlTlVRZmsyZDloTWluVUxGTGsyc3dCa2tVZERReEpYWUw5NE9INDFHQWNjRTFoSnRhUGJuNE5odmpmT0k4eW94TGs0UGkwYzlFOHFJbmJlanJISEhpTlFJMmVoYjVtX0xiakpCY0xlY3BQbklPRGN0UkYzSTdjemVlOWo1X2ZTd3E4Mko1RXFVQzdId243Z2FxOWRJa0VxZ2ZlQUdyUmFtYzhpdjFHekJ4ODlJMW52VDlWMmNLMXpkZmxDRVNIdDYxLTNLVXNHdHFpNjYtMGtSTjdMeTNrekY4UEdtLWE0ODZuZmR1cHdRTlFyNDlnOTFLTjBUU2NieEJiN3JWZzdUMWxMRWl6QVpRWE9rU0s2YmF1NTFaVTZOQkVlaE81UThyWlpNWlBDal9MU2pYVWp2b1dnPT0=\"",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1782978572,
        "storeId": null
    },
    {
        "name": "__Host-next-auth.csrf-token",
        "value": "a6675d3a8eae819b754dde92e742ffd943f45e0c2dcb4aca87b34791fc6fee42%7C2b727684001847e5914ba2e0cd9b3371e8b8dd9d98b0cfe08f3dfb352d6a6a47",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "__Secure-next-auth.callback-url",
        "value": "https%3A%2F%2Fchatgpt.com%2Cchat.gateway.unified-144.api.openai.com%2F",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "__Secure-next-auth.session-token.0",
        "value": "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..xnd-mdH16Nz5yHVQ.-SeJthkOHTBvOfjrSRssIS_QbcBFxo6plwu6YnarNxzRfDNBV2QQ-yzxcnLjrX1AhwDKD0yxaov00Y912FQ0eoG2LbairRq4Kq7HcoYWNdq6s--2DyEo5AYDRjjWwjRnfyw57aNuQmsiRJHdQQJ1qHO0E9-kZelVlZDaEVEFQh5NhTsX_jjtpXfP3fmIJxV08Lz896WFKVShZtR5e2WXqufy-5bzoQAHsmmsHgKKCeHXWh00jY34jgp-slbUWL8dIdEDRCSVh7GbjF1DhAhgYfluu2stQOMPPdvsC4ImTrFGKUTjlMa5FGTaUVjlO8-K9vJXoSfM-dMFzI7v7pDR8yD-z-6SK2qghHis8K11Q6wvrhj1Lra21IzouqYdYERqXrKkmG3I4TCTR8dzEdkLYDRKY_Wh97LWxFNfn12weUAG0wV055BDwAK1-1i8Ir3BfkORZXrtDn1SbTbc420E3Rzolfk20g2r2WdR19lv4t5v7CsKBAOTZIZoDSqoHA_zBRaw_XLjXKp4WsSXgjIrpeNwUevfkL2Px7R9N79Q63BTKQLwpzywp__GoM-tIcSnb11oyOKvlgvs2nlT51nj9AE26XD_WQ0jcBjhQaZYxHM4knN5fRc1NDcxOL1QvjRyB1ncEfh_a55Jwcx1br6rwY5hvvF38WUa3pNcJI0knUJH7xReFrYlr6ZrWh9aNNKB0nil3uB-uXG5h2SQ4DcbYKWWE_xYCLpQg5qbnM8PR0iNBxY9kMjPyFH841xbR-TUQxPDAjukSpHGeOpsKlXIpbN9oFzucw2vFaLDEhGqE9miaA9zkfpw0pQFLF5i-OtPcHwMx1lum-XQlQV805fR4WQFZSU9y98khVhs08GObeGoF7ecV6JpkGYvoaIrAerEM0q3OaS4duaddWoI7bZjXDt_kpVBtICh74c6D8YSKoNbIkUVme5OgqezHRkHwIEmRVFN_HBZDUec7HEYYK0p12JiP1xCUWiqh6On9oxy59C2jamcqXSJnHjqlBkJZj1PllgNjdg-CEpQ1jxXwyYgRZ-5B0t57j6FrJArWSHTvEgmhyx8wv2Y_mBTXKJcSYWCTpoulS8L0UEYvYjEva7HoE_tWnRXQayvmTts6ej2ebckOJtx963_svZSX30qF-4mkov8nk-cJ5fQikd7J2qj6sGrAUnk1n3304XRm_08uRj_XwA9vhJfwdcdZ_wRVwuK6EQO7aCXfrxWFD_dpF2RtTvnJV8EHXegrOirzRjQK-FrkjzkhY--hPHhZv-wyTXh1LUgSIcPVA0zyPHf_I-XT71yo5mVi59AgVoJhvzRIK0yhytW4CZ8RYXpTS4B9Hmm7pN6B7JFUvETc3fHd8FraCP7bsjF8VcWF3ZFnZE7jmHX64PAZX8x9sSEiv6tcZ6amO0dARLweuZyXdzLHWCcBl4IR08DxTH0wvgkSLo5pTRyZOksW9mDMXvNvcVfVL3QOTcSYwxyFeWUh9jkuljdbhcG71aViV-x3LvkFJ3urWfj4gzlr0IPvpI2bgOLpysGdA1lpi02ndO2-h7rowjC0lv-HkJj6hzkR4u7dslEsiPcZUrN-hUx5oBM0ISkP9Vr_wtg1dza9BK6wCEZhmyA1oKx55ORcXcX5WXMafz4ECmChbuIIYrGhR4muSFRnth2zkimQdZN9N7tYjY7QvZjgmkr1uFJvry0wDOuNglLWb0I3ftvx-sOzBQJLJRtvEFNA53kzr6-wQAciVSPAksjNITHZvjpycH4rzrva8CBrxOpZjBjchj3K6NvMRuLFXd9-Q7TU-FflSsROMrUwynXjfbI-Xp6WdXyyHiZFhEXPnv95-un7C7w1fr1KgN8XWvztqPzhFWRY1sEthXw-1WGhOZ2QbXy41pJBgd-qkyuurqNnu-UNQ1B4L2B-y-LFYXgfnxGCI3aSdlb-Wz84vaY9bkARi9uAwLLERoP36CaMrz4W6o6eDMbT5ffr1gErYUBnEl4dZAytojHS1RwTPSwu4KnHa08dZq892KLX7LufherJ3KE1VlXRCJUvkBQGiCtO-WHhvJ7y7oAfHjP1tH94kEZgkYQwC6g4byK8iF3x0SOHuFfAdGuZiIJ-hA68uNcK5guVr33iooKLR4e1hdluYnca4EgXosg6bSWyhnWls9wWFjzNeZDB-AEYMu0-yIz6j_-OOYDqT2p-kQQ-uvAlLm_TfHp2pFyA6WcArYehjN4xpexNxceZ-OFtaWiSW8GiNEa4SnqVQdL5oj7bLmC638WlT9hIO3O2wfjV9YBPw9ZBhWo-FXDGeK348uOA7E5wlO9PQptcDiCMtNLywXBrjpFFZKDrw6lfQ4rn0v5wWC1O5Oy5tgbziFe1aKxhqh00aXmMbZr5NgoaNrkGY4x2Tlft09l8hWI0aPCWzHwyTdO7fLS5CKTbV74TifzxkQgx3mc4LdW9aYiZPRCYgWQK8J1eD751PcOUhHJ73a4wZLd5T7M034D3Hade3C7wTeNZ81AU6DYyYMzCCnI1_w9MFnfttsyp-sfwEum3C3Tvr1wBQgaj2ufpwkhnDayv6QuagNuSPBM84BjjL_-MwsJCY0zfiBAn8ORhz8kVKerlvl_bYZPHopjWt7bIXyssqrMmQXA-MtevuBmiFjEmAe70pmsvYc6EMDLoX7j55PZsAMuJjd4-STK_5O5JvcAOhl6qrKU9bZhHoO8gvjbJQE-nSdZ-uAwV-OZab6fcDADK4nkq4sj44AqmfadjBOzsGpdoTxrAkJmKOucroB9mTxEgSgDwCORwqpcklneF34TrOhURuz80cpnLRGDE0oipj1UyJ44QPIw3Vi9vRfJB75falK7KkNxwT77tanAn-Me4cbxcCDIRsy1I34AiS-KZ7tYFjKkjcZ3wXJt6INIqbB-cRAQMEgNMNZ_INuGdoEERRHrvnyfexsk70su_tfk86JwsUKbhWIQ9hhLoBIkoM6oOE9tKGf6drF-8nU7yijC9w0t5ga-VKDG-5l0n6NfO9aiipgEcEmc740wlDQwNXi41QV0oQ6ySijtX5Z0W5QlZRZXNHOmq-kWk5VQGuWpypwSWeFg0q9f5eJl2g45V71APhKOERNlkiFJzA_ffHZaQIg0jrf8ju5wPb1syyzeVWxwkZXsRdPvVSb6OSKcl7e08gzcORAv27ARtgWkH5UWY5t_pd0c0v6hzKTLbU0rDvNN0x2oD6imaM78wFi1GvGgDqWRUEH5cSOARyJzVpVZQdUHh6ebU5DScMKcvCp5wkXPBBz_YYQ2kvRYdAeKQPOq9gRLAsVp54sejUqpalQc1gYKz1Cy8bQoyIKhQD5R5YE04-UHZ0jTTpi6LKOL-OV4sAuiYs0SOT5bMdKDWKGNuHPLXU3bKwMEr5mxX3CL9mK8INMJgwPwbpdh_NmztOdA52LxHoDaoEaQDYkP9vqYyAcQOhDwjueXEnHCDqQtPWsaviteoeRCrJdBABqnj813E0atBfS9Om8OObVWDPX8RwEVOv91PTd3YEaz1yap0XgZDWEjf9LF66lx5ddXdw5dVjqq-QN9ZNt0M1p4iLa29umMpaASdFOAUHCXre9FimZouCgdMKQgfmvx6Lz2tFJHcp9kwRBC44yeTVqzCeLWzsCsdZgqGIxtbEFenBlVlzslxbOxh-oG8bqfGdeyu_gr5b-KzMMceYKroq6295MV-3ZniA0IM1wv7-AEgNsPUvCNEVEmA0y0RboijO7HSLm6Hnd_Djw933Wd3uVlju2df8wx6bzq37trbf4Uf1s-N0lzwmO0ypzpjNRG1QTjtqVQQhAPguFjqjcpicCBUfPqIL4tE50RmwTzSm778wHbMM0lRezT2mBrnMjO7X2_BUKD9NTlRZ97XQdPVvE",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1791112929,
        "storeId": null
    },
    {
        "name": "__Secure-oai-is",
        "value": "ois1.eyJ2IjoxLCJhbGciOiJBMjU2R0NNIiwia2lkIjoiY2hhdGdwdC13ZWItdjEifQ.q-xdH_KfIV57XAek.5dZBeGYWmtZEUcw_61CAEVjsjwRWsX75G-hRbiVfY0madYxzh513TxQgeeo4-InnvK9GeV0tNsqKlS6gIIM4YcQv-WlPd3WO0OyxIU8iHeKTp7m0J-kUD5j8fsjlgZkenX9MBILiremFgfYSEPMVdDtNBMH1P04HQXekLPwlOGbCwcDHafq3DjSq7w0K9b-EL-e1T8TlmINDcWqSiGBi-wqKvcOdnlnc3X4XDioV8YoES4vidb0p4R_eyGaV7LbHsxuPDwfZGMTOOUadsvhgiQbFMz6F0Kqk6WV6AEBcE-6j09vNnEMmmceS53SUT8_DDhM8QMR0oqZG4XtAZ0XlAxgtOniNvYp4-s-GtRexDth8jn9rznn7YHNsIgatXEWRiTOcRoCfUFwK-bd2bMTtXNGa4q65LwdKuH2POTCc3-8Lg_Uw4p77avjf0N_o_MySv5EIVkEw0KgFaC2F2yZZVa1AjEeSBTjFmsQ1AtWu1PC7x0xr81WiwZxKsg724jy3TFWv7IY4k04-M9LgE4V18g96qq4jZHnlz8TRSod0UXw_qyRceh_QHcXVp2wvx8j3HAldVUI69lqqpnuppGhEITFFd6cGcFSK7rfQ4_pacdcYp1Y3XsrEI0jJdKg4aRHknIlqG5Mal_hnpHL4p-9qeoTH6fG9YWesirw8AUeOTIWPObQ2WQaOJDBDDTolSlGntUjF8I_Seyo2dznzPwXsvFtKMBzsxJOlGfrPtzt7lA1rdVwh8oCoI3GeHpgMX-ZplPloQGAhysIOF16UETSz_34DFuULrHpAfHxRK0xk7Nv3T4ArVZhO2lEQ-m4hkKXDUA_U4sgToOTNqiEUIBPgQTIymI1to-32NE2CFNX4tWMf4ABfdYvzm569VdZoJU_SMaZQ_qOL0kf-uFdqXHRrDb3jiJFRoEzVsWo6k1MJZ53NW7hVpRQvC3kAmCBboqD0PI2Qb8P8DM3K3X4_xcFC5E-1zfiu0srOiaJNipJY0KbBHa4Z5CJSy2Z6XZcqtvdARtVplskJ3k3J83xxw2Z1glBH5wzzNR1GjJ_grK2geJF8tAyPkCog0CAETAx1_BlxDPDokcAG0h6mMqZA3QGdRzkgxv6BsXVwkHnHp6wHki7u9JKSCnztkrXAcXNypkgEpk1Yyp89el__5g1skqZdoa5Js1BrH_3_VCcMGT-j8mHS_1eZzFYptAX6vk-T6tCsYjH5kq8IM-3EUNOiWA-2eU6WU_DCZLb0FNbKBckUbSaCV5RGR05iC09AEAbZM_TXZXf1GMAuHWL_TbB1hn6-qMbMP8nyyV6tBPOcrghXe4GFFqC31tH-RLsY4u4wNd7jjt2_AcEjLfsuYMZG3WObSXAUoMnBmsWDVe4Si1ZlkmiXlft6nSqWT9SY9H-URfwMOqf6-RgbMSufq4JrNsNaN7Vs0D_UgttOPN1yr-nxG9QoRcxxMjbf_aeBHWRQoJp2ldgJqBXW5V7TIq78NHmqgUmfM_tvwMvXnuHylSaGLb7fAKoPPhVdeFrNN4YOGnvJXvdeh-zvgIW0WXkAIZd_lfBRMF9xNatxLo8ffDD3Os22uRi9JQMu7Vg-1VfNGyxobrnw3cMYz1Psg4NNI-_u6HeRZX3cm2zqf-Xi_Zc9UwB7lRr7TiUVLdGAIxg1tFqMUb7bMemHqOpGDfA-hB3XQQM5WkhNb3aOeS5fm4agvzNL2d5gM_7ATi7tLwrRYfSvKssI4vIr41ngmttIO09M7pmPPbVCU9944Pcm0fqsDX8xyoNj-lKkj4lGx2ifa3vx0flnHRDeVS30CB0ikp25sd9i-1QMbVPliUw6C_aKTIus3N6tDBf6VnzzPm5XZPbCpmDIoVNX-4JR7wTwMGQDL8TpnQ",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1785928933,
        "storeId": null
    },
    {
        "name": "_umsid",
        "value": "\"Z0FBQUFBQnFSaEVGZUZ2RDU4TVItdVlucTV2RnlQWVRoMXJPTHV4SlRrQ2wyREtQVkNCMm1MYnFvVU5GeVlRZ0NEYXU3WThuRnlrdVFBdHVyQld3dTRKOFl2bzhqQlV1dzJ1M2JUVFJBM1V4TmVTNzluS0xTb1ViMEhScExzakcxU0owdzlreHphQVljcENZcDVTbjl0NWh5MC1kOVRScXFhTTZYRmVqbF9wRGxEdU56MmNzYjZWYVdaZzRKY21vUnVjakk2X0xxTzd2ZG9zVmNZaS1tRDZMenJnT1dzYlo3TkNvVWNiNEdtdTAtQVpaZmUyVnJMWT0=\"",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1782978572,
        "storeId": null
    },
    {
        "name": "g_state",
        "value": "{\"i_l\":1,\"i_ll\":1782976551031,\"i_e\":{\"enable_itp_optimization\":24},\"i_et\":1782976551031}",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": null,
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1798528557,
        "storeId": null
    },
    {
        "name": "oai-allow-ne",
        "value": "false",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1798528566,
        "storeId": null
    },
    {
        "name": "oai-client-auth-info",
        "value": "%7B%22isOptedOut%22%3Afalse%2C%22loggedInWithGoogleOneTap%22%3Atrue%2C%22user%22%3A%7B%22name%22%3A%22Winda%20chann%22%2C%22email%22%3A%22windachan762%40gmail.com%22%2C%22picture%22%3A%22https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fwc.png%22%2C%22connectionType%22%3A2%2C%22timestamp%22%3A1783336933169%7D%7D",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1785928933,
        "storeId": null
    },
    {
        "name": "oai-did",
        "value": "8cc959bb-0ccf-4bee-a4bb-945db989d645",
        "domain": ".chatgpt.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1814080547,
        "storeId": null
    },
    {
        "name": "oai-nav-state",
        "value": "0",
        "domain": "chatgpt.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1817536895,
        "storeId": null
    }
]`;

(async () => {
    const { parseCookie } = require('./puppeteer_core');
    const parsed = parseCookie(cookieStr);
    console.log("Parsed JSON Array Length:", parsed.length);
    console.log("First cookie structure:", parsed[0]);
    console.log("Checking for undefined or invalid fields...");
    parsed.forEach(c => {
      for (const key in c) {
        if (c[key] === null) console.log(`Null value in ${c.name} for key ${key}`);
      }
    });
})();
